- name: Instalación entorno LAMP en contenedor ubuntu-test
  hosts: all
  become: yes
  vars:
    mysql_root_password: "test"
    mysql_db: "tienda"
    mysql_password: "test"
    script_sql_local: "{{ playbook_dir }}/data_base/bd_tiendaonlinenueva.sql"
    script_sql_container: "{{ playbook_dir }}/bd_tiendaonlinenueva.sql"

  pre_tasks:
  - name: Instala PyMySQL
    pip:
      name: PyMySQL
      state: present
    tags:
      - pretask

  - name: Copia el script .sql al contenedor
    copy:
      src: "{{ playbook_dir }}/data_base/bd_tiendaonlinenueva.sql"
      dest: /home/ansible
      mode: 0744
    tags:
      - pretask
      - bd

  - name: Copia el codigo web a /var/www/html
    copy:
      src: "{{ playbook_dir }}/www/"
      dest: /var/www/html/
    tags:
      - pretask
      - web

  # MYSQL
  tasks:
  - name: Instalación MYSQL
    apt:
      update_cache: true
      name: mysql-server
      state: present
    tags:
      - mysql
    
  - name: Arrancamos MYSQL
    service:
      name: mysql
      state: started
    tags:
      - mysql

  - name: Archivo de configuración para cliente MySQL login de root
    copy:
        dest: "/root/.my.cnf"
        content: |
          [client]
          user=root
          password={{ mysql_root_password }}
        mode: 0600
    tags:
      - mysql

  - name: Cambio opciones de método de autenticación para el usuario root, permisos y passw
    mysql_user:
      login_user: "root"
      #login_unix_socket: "/var/run/mysqld/mysqld.sock"
      name: "root"
      password: "{{ mysql_root_password }}"
      priv: "*.*:ALL,GRANT"
      append_privs: yes
      state: present
      check_implicit_admin: yes
    become: yes
    become_user: root
    tags:
      - mysql


  - name: Crear la base de datos
    mysql_db:
      name: "{{ mysql_db }}"
      state: present
    become: yes
    become_user: root
    tags:
      - mysql

  - name: Importar script SQL para la base de datos
    mysql_db:
      name: "{{ mysql_db }}"
      state: import
      target: "{{ script_sql_container }}"
    become: yes
    become_user: root
    tags:
      - mysql


  # APACHE
  - name: Instalar apache
    apt:
      name: apache2
      state: present
    notify: reinicia apache
    tags:
      - apache

  # PHP
  - name: Instala la última versión de PHP disponible
    ansible.builtin.shell:
      cmd: |
        apt-get update -y
        DEBIAN_FRONTEND=noninteractive apt-get install -y php php-mysql libapache2-mod-php
      executable: /bin/bash
    tags:
      - php

  # Reiniciar apache
  handlers:
      - name: reinicia apache
        service:
          name: apache2
          state: restarted
